### ISSUE TITLE
Uniformize code syntax 

### ISSUE THREAD

**Issue by gcode-importer** [uclouvain/openjpeg#128]
Originally reported on Google Code with ID 128

```

see http://code.google.com/p/openjpeg/wiki/CodingStyle
```

Reported by [detonin](https://github.com/detonin) on 2012-02-20 16:22:14

**Comment by stweil** [comment]
Indenting with tab characters (instead of spaces) is only an acceptable choice with a fixed tab width of 8 (that's the style used for Linux kernel code).

I personally prefer indentation with spaces, either in steps of 4 (preferred, used for many free software projects) or 2.

**Comment by boxerab** [comment]
This tool might be useful here:  http://astyle.sourceforge.net/

an automatic formatter. You can specify the style you would like, and it will run through all source code files and re-format.

**Comment by stweil** [comment]
Yes. I can confirm that astyle works pretty good.

**Comment by detonin** [comment]
I gave astyle a try and pushed the result on the "codingstyle" branch, together with the config file I used (see tools/cstyle/opj_astyle.cfg in that branch). Plan is to merge it into master once we agree on the config file. Btw, is it better to do this just before the release or just after ?

Comments welcome.

There was also uncrustify proposed by @malaterre a while ago.
My opinion is that astyle works fine and seems simpler and lighter than uncrustify. Being simpler is an advantage if we want any contributor to process its PR through astyle before submitting.

@mayeut Do you think it would be possible to add a test in Travis to run astyle with the opj config file (might be in dry-run mode (--dry-run option)), and return a failure if there is any file being marked as changed ? The idea would be to merge PR only if it meets opj coding style.

**Comment by mayeut** [comment]
My comments, all this is only a personal preference of course.
- I'm ok with k&r (c.f. minor comment below) or allman style. I usually mix them which is bad... (k&r for short blocks, allman for longer blocks . I find it more readable mixing the 2 for some reason.)
- If spaces are to be used, I'd rather see it in steps of 2. I find this easier to read, especially with many indentations levels where lines are either not fully readable (cropped by limited screen width or wrapped depending on preferences on this matter)
- with astyle, I'd probably add `--break-closing-brackets` if k&r style is used (the following is from style documentation:
```
void Foo(bool isFoo)
{
  if (isFoo) {
    bar();
  } else {
    anotherBar();
  }
}
becomes (a broken 'else'):

void Foo(bool isFoo) 
{
  if (isFoo) {
    bar();
  }
  else {
    anotherBar();
  }
}
```

**Comment by malaterre** [comment]
The new kid in town is (clang format)[http://clang.llvm.org/docs/ClangFormat.html]

**Comment by stweil** [comment]
@detonin, I suggest to start with existing pull requests which fix some smaller formatting issues (#678), then pull all other requests which are suitable for the next release, then make the release, and reformat the code at the beginning of the next release cycle.

Existing pull request will usually need more or less re-basing when the whole code gets reformatted, therefore it is good to apply them before that action.

I had a look on your astyle configuration and think that it is a good starting point. `--convert-tabs` is an important option needed to remove all tabs (not only at the beginning of lines). What about limiting the length of code lines (for example `--max-code-length=80`)?

I tried this set of options:

    --convert-tabs
    --lineend=linux
    --indent=spaces=4
    --style=kr
    --exclude=thirdparty
    --exclude=wrapping
    --add-brackets
    --max-code-length=80
    --break-after-logical
    --pad-header
    --pad-oper
    --unpad-paren
    --recursive
    --suffix=none

In most cases it seems to give good results, but astyle is not perfect, so some options (for example `--pad-oper`) sometimes fail to improve the code. That's why I'd not add a Travis rule to check code formatting (or only a simply one which checks for forbidden tabs, wrong line endings, lines which are too long).

**Comment by hjmjohnson** [comment]
personally, I am very excited to see this discussion.   Providing consistent code is key to long term maintainability of a code base.

**Comment by hjmjohnson** [comment]
You might be interested in the discussion here:  https://github.com/vxl/vxl/issues/164

**Comment by julienmalik** [comment]
See also discussion here : https://github.com/vxl/vxl/pull/145

**Comment by julienmalik** [comment]
Maybe clang-format is more future-proof.
It already has plugins for a number of editors (see http://clang.llvm.org/docs/ClangFormat.html, and plugins for other editors can be found), and the clang community is huge, so I'm less worried about its maintenance.

**Comment by detonin** [comment]
yes, i tend to agree with you @julienmalik. I'll give a try to clang-format on the codestyle branch. Do you have a config file or a set of options to suggest ? (see https://github.com/uclouvain/openjpeg/issues/128#issuecomment-175076907 for a proposed set of options for astyle)

**Comment by malaterre** [comment]
@detonin I would really suggest using one of the default (eg. 'llvm'). This will kill any debate on which one is best.

Eg:

`$ clang-format -style=llvm -dump-config > .clang-format`

**Comment by stweil** [comment]
I just tested clang-format-3.8 on Debian stretch and are really impressed by the result. The formatter not only re-formats the code, but also sorts include statements alphabetically. I like that, but of course it can also break compilation, so further tests are needed whether this feature of `-style=llvm` is acceptable. The indentation with of 2 is small, but IMHO sufficient. Personally I'd prefer using `{}` even for blocks with a single statement. clang-format removes them for `llvm` style.
But to summarize, I think that using clang-format would be a good thing, and the `llvm` style is a good starting point - maybe initially without sorting of include statements.

**Comment by julienmalik** [comment]
Personnally I don't care much about the actual style settings.
Just choose arbitrarily, or ask @mayeut to choose since he is the most active contributor at the moment.

@stweil I think you raise a good point with the single statement blocks.
This is not consistent currently, even after a pass with clang-format (llvm style) : clang-format with llvm style does not seem to *remove* the braces, but instead *allow* to have braces or not. I also don't like single statement blocks, feels unsecure to me for maintenance (what if the statement is a macro, like in dwt.c where these single statements appear a lot).
See [this](http://stackoverflow.com/questions/26111162/can-clang-format-add-braces-to-single-line-if-statements-etc#28437960) : this seems like to be the job for another tool, clang-tidy (see [here](http://clang.llvm.org/extra/clang-tidy/checks/readability-braces-around-statements.html))...

**Comment by hjmjohnson** [comment]
I want to agree whole-heartedly to the preservation of {} even for single statement blocks.  I believe it makes the code more robust to future changes.
I would also advocate for 2 spaces indentation.  

Hans

--

**Comment by mayeut** [comment]
Now would probably be a good time to do something.
There's been a major code change so PR won't be affected by this (they're already affected by the major code change).

Agreed with @malaterre `clang-format -style=llvm -dump-config > .clang-format`
Also, adding braces for single statement blocks would be a nice add-on. Unfortunately, as @julienmalik pointed out, clang-format won't add/remove those (from the links he refers to, clang-format only acts on whitespace characters). clang-tidy shall be used for that but that's another story.

**Comment by detonin** [comment]
@rouault with the new optimization plan starting, it would probably be a good time to fix the code syntax (or maybe after some of the most relevant PR have been merged). Could you have a look to this also ?

**Comment by rouault** [comment]
Is there some concensus on this : both regarding the tooling and the style settings ?
I know that some projects like QGIS use astyle and have actually embedded the source code of a given astyle particular version in their repo so that the output is the same for everybody and doesn't depend on the version in their system

**Comment by rouault** [comment]
The issue with setting a style code is that you need to enforce it afterwards otherwise it is pointless. And you need to provide the means to people to easily comply with it, whatever the editing tool they use. That's one of the thing I like with QGIS. I do't care about the code style to apply: I just run scripts/prepeare_commit.sh before committing and it reformats it in a compliant way. And there's a Travis check for that. Honestly if I were to do act on this subject, my preference would just copy&paste what QGIS has done in that area (they use cmake too so this should be relatively easy to port).

**Comment by stweil** [comment]
Copy & paste from QGIS is not possible because of incompatible licenses.

**Comment by rouault** [comment]
> Copy & paste from QGIS is not possible because of incompatible licenses.

I don't agree with that. Any free and open source license is fine for tooling. We just need to ensure that the library code is BSD 2. Your compiler is tooling and if it is GCC it is GPL'ed.

**Comment by stweil** [comment]
You can use the QGIS code for tooling, yes. But I don't think that it is allowed to add GPL code to the openjpeg repository which uses a BSD license for the whole repository. So the GPL'ed code would have to be separated from the repository (like gcc).

**Comment by stweil** [comment]
As far as I see the most important part of the QGIS code which is needed for openjpeg is the code formatter. QGIS‌ also uses spell checking and more tools which IMO are not needed now.

QGIS uses astyle. It includes the code for astyle. This is not necessary – pre-compiled astyle binaries are available for all common systems. So there remains mainly the configuration file for astyle. I don't see a problem in using a small configuration file which typically is not copyright protected.

**Comment by rouault** [comment]
https://github.com/uclouvain/openjpeg/tree/master/thirdparty includes software under other licenses. I have not the whole history of QGIS regarding the internal astyle version but I guess the reason must be that the output of astyle might change from one version to another one and bundling it make it easy to ensure that everyone runs the same (or perhaps it was added at a time where astyle was not widely packaged). That said, if that seems to be a problem, we could decide on a given reference astyle version and people would possibly have to build it if their packaged version differs in output.

**Comment by malaterre** [comment]
@rouault why are you talking about `astyle` ? I thought we were going for `clang-format -style=llvm -dump-config` ?

**Comment by rouault** [comment]
@malaterre I was talking with astyle because I'm familiar with its use with QGIS and I like being in known territory :-) Well, if the concensus is for clang-format, I'm ok with it.

**Comment by detonin** [comment]
@malaterre We were indeed talking about clang-format but I don't remember that there were any strong objection to use astyle instead (or any strong argument making clang-format a better option). If @rouault is to add this, I would be in favour of choosing a known territory for him :).

Moreover, concerning braces around single statements, it seems astyle does this with the add-braces option: http://astyle.sourceforge.net/astyle.html#_add-braces
As far as I understood, clang-format does not, and requires another tool (clang-tidy) to deal with these cases. So one more point for astyle.

Concerning config, I propose we start from the QGIS config and update it accordingly to make sure single statements are enclosed with braces.

@stweil concerning licenses, the thirdparty folder indeed already contains libraries with different licences so we could put astyle code there.

**Comment by malaterre** [comment]
@detonin Obviously is @rouault knows `astyle` there is no point in arguing for me.

As a side note I could find the option `AllowShortBlocksOnASingleLine` from the online documentation:

* https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by detonin** [comment]
@malaterre Thanks Mathieu.
As far as the option you mentioned is concerned, in my understanding it *allows* blocks for single statements but does not add (or remove) braces. See this comment from Julien a while ago: https://github.com/uclouvain/openjpeg/issues/128#issuecomment-215403212

**Comment by detonin** [comment]
@rouault let's go for the QGIS/astyle way then :)

**Comment by rouault** [comment]
See https://github.com/uclouvain/openjpeg/pull/919
