### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by bitsgalore** [uclouvain/openjpeg#1513]
## Expected behavior and actual behavior.

...to fill...

## Steps to reproduce the problem.

...to fill...

## Operating system

...to fill...

## openjpeg version

...to fill...

**Comment by rouault** [comment]
yes, this is a known issue (CC @detonin )

**Comment by bitsgalore** [comment]
@rouault  Ooops, I accidentally pressed send before entering the actual description, sorry for that! In short the problem seems to that the template refer to various non-secure resources (CSS, but also images), which by default get blocked by most browsers. Un-blocking results in correct rendering.

**Comment by detonin** [comment]
Hi Johan, many thanks for your input ! Well, the issue is known in the sense that I noticed that the jekyll template I used by then is not correctly rendered by github anymore (it's not rendered at all actually). I was thinking of replacing completely the template by another one but if you think of sth easier to do to fix it, I would be more than happy to implement it :).

**Comment by detonin** [comment]
ping @bitsgalore (no rush btw: this is just in case you do not receive notification without explicit tagging)

**Comment by bitsgalore** [comment]
@detonin I'll try to have a look, hopefully next week.

**Comment by detonin** [comment]
Fixed this and took the opportunity to switch to Github Actions (as the legacy builder will be deprecated soon.
The issue was due to the enforcing of https.
@rouault : Should work properly now
