### ISSUE TITLE
No colorspace information after opj_read_header

### ISSUE THREAD

**Issue by HGuillemet** [uclouvain/openjpeg#570]
image->color_space and image->icc_profile\*  are only filled in opj_decode() and not in opj_read_header(). This is problematic in situations where the color space must be know before decoding pixel data.

This should be easily fixable by moving from opj_jp2_decode() to opj_jp2_read_header() most of the code that copies color information from the jp2 struct to the image struct.

**Comment by lrosenth** [comment]
Indeed, this is necessary. I have cases where I need the color space information before decoding the image.

**Comment by sebras** [comment]
I recently discovered the same. Only after calling `opj_decode()` is `opj_image_t->color_space` set. [Others](https://groups.google.com/forum/#!topic/openjpeg/hmdymiSSh50) have been asking for the same.

Would you accept patches to try to move the colorspace detection code to some function called by `opj_read_header()`? Maybe there is a reason for why the colorspace is not available until after image decoding?

**Comment by mara004** [comment]
@ OpenJPEG developers: any comments on this issue?
PDFium's `FPDFImageObj_GetImageMetadata()` function is affected by this problem, too.

**Comment by rouault** [comment]
attempt fix in https://github.com/uclouvain/openjpeg/pull/1463 . I'd appreciate if reporters could test that it actually fixes the issue (I'm not sure openjpeg test suite tests that)

**Comment by rouault** [comment]
@mara004 Did you have a chance to test https://github.com/uclouvain/openjpeg/pull/1463 ?

**Comment by mara004** [comment]
@rouault Unfortunately no, as I'm not using openjpeg directly, but only through pdfium, which bundles openjpeg.
However, I think pdfium may benefit from the change once they update their copy of openjpeg.

Apart from that, could you add a test case to confirm your implementation works?

**Comment by sebras** [comment]
@rouault I did a little investigation. I think changed so that one can access normal colorspaces after calling `opj_read_header()`, but not ICC profiles (they still require a call to `opj_decode()`). So unfortunately I think you only adressed half the bug.

As I understand it [file1.jp2](https://github.com/uclouvain/openjpeg-data/blob/master/input/conformance/file1.jp2) from your testsuite sets sRGB in its COLR box. And now after your commit I see that `->color_space` is set to `OPJ_CLRSPC_SRGB` immediately after the call to `opj_read_header()`, i.e. no need to call `opj_decode()` to determine the colorspace.

As for ICC profiles [relax.jp2](https://github.com/uclouvain/openjpeg-data/blob/master/input/nonregression/relax.jp2) appears to set an ICC profile in its COLR box and after the call to `opj_read_header()` then `->icc_profile_len` and `->icc_profile_buf` are not set. However after I have called `opj_decode()` both will be populated and I can retrieve and analyze the colorspace.

**Comment by rouault** [comment]
pull request amended to move ICC profile setting to image in read_header()

**Comment by sebras** [comment]
@rouault Thank you for fixing this! :)
