### ISSUE TITLE
ETS-C1P0-p0_12.j2k-compare2ref & NR-C1P0-p0_12.j2k-compare2base failing under windows

### ISSUE THREAD

**Issue by mayeut** [uclouvain/openjpeg#655]
Those tests are failing under AppVeyor since AppVeyor update on November 6th.

**Comment by boxerab** [comment]
I think I know what is going on here:  on windows, depending on the configuration, Git will convert LF to CRLF if it thinks the file is a text file. So, the test is failing because the corresponding PGX reference image gets corrupted by git checkout.  See [here](http://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf)  for more details.

**Comment by detonin** [comment]
https://github.com/uclouvain/openjpeg-data/commit/3165ff6f56e1471f51b510400a5460d0fb4df7d7
