### ISSUE TITLE
Not conformant to standard on windows

### ISSUE THREAD

**Issue by boxerab** [uclouvain/openjpeg#897]
This conformance test fails:

     49 - ETS-C1P0-p0_12.j2k-compare2ref (Failed)

So, it seems that the library is not conformant to standard on windows.

On Linux, this test passes.

**Comment by boxerab** [comment]
This image is encoded using RESTART mode, so since this mode is broken at the moment, it breaks this conformance test.

**Comment by detonin** [comment]
@boxerab this test fails since an AppVeyor update made on November 6th, 2015 (not a code update) and it has already been reported in #655. As it passes on Linux, I do not see any strong argument in favor of RESTART mode being responsible for this. This is the second time you are duplicating an existing issue, may I ask you to more carefully check whether it has already been reported ? If so, feel free to continue the discussion in that thread (#655 in this case).
